import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f3efe7' },
  container: { padding: 16 },
  loadingText: { padding: 24, color: '#18231c' },
  heroCard: { backgroundColor: '#20404f', borderRadius: 24, padding: 20, marginBottom: 20 },
  eyebrow: { color: '#cae3ef', fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8 },
  title: { color: '#fff', fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle: { color: '#d7ecf5', fontSize: 15, lineHeight: 21 },
  statsRow: { flexDirection: 'row', marginTop: 16, gap: 12 },
  statCard: { flex: 1, backgroundColor: '#2f586b', borderRadius: 16, padding: 14 },
  statValue: { color: '#fff', fontSize: 22, fontWeight: '700' },
  statLabel: { color: '#d7ecf5', marginTop: 6, fontSize: 12 },
  warningBanner: { color: '#fff7d1', marginTop: 10 },
  card: { backgroundColor: '#fffaf2', borderRadius: 22, padding: 18, borderWidth: 1, borderColor: '#eadfca', marginBottom: 16 },
  tabBar: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tabButton: { flex: 1, backgroundColor: '#dfe8df', borderRadius: 18, paddingVertical: 12, paddingHorizontal: 14 },
  tabButtonActive: { backgroundColor: '#20404f' },
  tabLabel: { color: '#20404f', fontWeight: '700', textAlign: 'center' },
  tabLabelActive: { color: '#fff' },
  routeBanner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, paddingHorizontal: 4 },
  routeText: { color: '#5f6d64', fontSize: 13, fontWeight: '600' },
  routeActionText: { color: '#20404f', fontSize: 13, fontWeight: '700' },
  sectionTitle: { color: '#18231c', fontSize: 22, fontWeight: '700', marginBottom: 12 },
  listCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5', marginBottom: 10 },
  listTitle: { color: '#18231c', fontSize: 17, fontWeight: '700', marginBottom: 4 },
  listMeta: { color: '#5f6d64', fontSize: 13, marginBottom: 6 },
  listBody: { color: '#425046', fontSize: 14, lineHeight: 20 },
  listHint: { color: '#20404f', fontSize: 12, fontWeight: '700', marginTop: 8 },
  detailGrid: { gap: 10 },
  detailSection: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5' },
  detailSectionTitle: { color: '#18231c', fontSize: 16, fontWeight: '700', marginBottom: 8 },
  bulletRow: { color: '#425046', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  navRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16, justifyContent: 'flex-end' },
  logoutChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: '#6b5b55' },
  logoutText: { color: '#fff', fontWeight: '700' },
  modeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  modeChip: { flex: 1, paddingVertical: 10, borderRadius: 999, backgroundColor: '#e4e0d6', alignItems: 'center' },
  modeChipActive: { backgroundColor: '#20404f' },
  modeChipText: { color: '#324138', fontWeight: '700' },
  modeChipTextActive: { color: '#fff' },
  infoBanner: { color: '#8b5e34', backgroundColor: '#fff3cd', borderRadius: 14, padding: 12, marginBottom: 12 },
  errorBanner: { color: '#991b1b', backgroundColor: '#fee2e2', borderRadius: 14, padding: 12, marginBottom: 12 },
  input: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#d8ddd6', paddingHorizontal: 14, paddingVertical: 12, color: '#1f2937', fontSize: 15, marginBottom: 12 },
  textArea: { minHeight: 100, textAlignVertical: 'top' },
  primaryButton: { backgroundColor: '#d76c45', borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  secondaryButton: { backgroundColor: '#5d6e78', borderRadius: 14, paddingVertical: 12, alignItems: 'center', marginTop: 10 },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 }
});