import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f4efe6' },
  container: { padding: 16 },
  loadingText: { padding: 24, color: '#18231c' },
  heroCard: { backgroundColor: '#294936', borderRadius: 24, padding: 20, marginBottom: 20 },
  eyebrow: { color: '#d7eadb', fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8 },
  title: { color: '#fff', fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle: { color: '#e2f0e5', fontSize: 15, lineHeight: 21 },
  statsRow: { flexDirection: 'row', marginTop: 16, gap: 12 },
  statCard: { flex: 1, backgroundColor: '#375c46', borderRadius: 16, padding: 14 },
  statValue: { color: '#fff', fontSize: 22, fontWeight: '700' },
  statLabel: { color: '#d7eadb', marginTop: 6, fontSize: 12 },
  warningBanner: { color: '#fff7d1', marginTop: 10 },
  infoBanner: { color: '#8b5e34', backgroundColor: '#fff3cd', borderRadius: 14, padding: 12, marginBottom: 12 },
  tabBar: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tabButton: { flex: 1, backgroundColor: '#dce7dd', borderRadius: 18, paddingVertical: 12, paddingHorizontal: 14 },
  tabButtonActive: { backgroundColor: '#294936' },
  tabLabel: { color: '#294936', fontWeight: '700', textAlign: 'center' },
  tabLabelActive: { color: '#fff' },
  routeBanner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, paddingHorizontal: 4 },
  routeText: { color: '#5f6d64', fontSize: 13, fontWeight: '600' },
  routeActionText: { color: '#294936', fontSize: 13, fontWeight: '700' },
  card: { backgroundColor: '#fffaf2', borderRadius: 22, padding: 18, borderWidth: 1, borderColor: '#eadfca', marginBottom: 16 },
  sectionTitle: { color: '#18231c', fontSize: 22, fontWeight: '700', marginBottom: 12 },
  subheading: { color: '#425046', fontSize: 14, lineHeight: 20, marginBottom: 10 },
  listCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5', marginBottom: 10 },
  listTitle: { color: '#18231c', fontSize: 17, fontWeight: '700', marginBottom: 4 },
  listMeta: { color: '#5f6d64', fontSize: 13, marginBottom: 6 },
  listBody: { color: '#425046', fontSize: 14, lineHeight: 20 },
  listHint: { color: '#294936', fontSize: 12, fontWeight: '700', marginTop: 8 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: '#dbeadf' },
  chipText: { color: '#294936', fontSize: 12, fontWeight: '700' },
  actionRow: { gap: 10, marginTop: 12 },
  primaryButton: { backgroundColor: '#d76c45', borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  secondaryButton: { backgroundColor: '#5d6e78', borderRadius: 14, paddingVertical: 12, alignItems: 'center' },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  detailGrid: { gap: 10 },
  detailSection: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5' },
  detailSectionTitle: { color: '#18231c', fontSize: 16, fontWeight: '700', marginBottom: 8 },
  bulletRow: { color: '#425046', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  reviewTitle: { color: '#18231c', fontSize: 18, fontWeight: '700', marginBottom: 6 },
  reviewMeta: { color: '#5f6d64', fontSize: 13, fontWeight: '600' }
});
