apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "orchestrator-model.fullname" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "orchestrator-model.fullname" . }}
  service:
    port: {{ .Values.service.port }}
  analysis:
    interval: {{ .Values.canary.analysisIntervalSeconds }}s
    threshold: 5
    maxWeight: {{ .Values.canary.maxWeight }}
    stepWeight: {{ .Values.canary.stepWeight }}
    metrics:
      - name: request-success-rate
        threshold: 99
      - name: request-duration
        threshold: 500
    webhooks:
      - name: rollback
        type: pre-rollout
        url: http://example.com/rollback-hook
