import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f1f2ec' },
  container: { padding: 16 },
  loadingText: { padding: 24, color: '#18231c' },
  heroCard: { backgroundColor: '#3c3a56', borderRadius: 24, padding: 20, marginBottom: 20 },
  eyebrow: { color: '#d7d4f0', fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8 },
  title: { color: '#fff', fontSize: 28, fontWeight: '700', marginBottom: 8 },
  subtitle: { color: '#ece9ff', fontSize: 15, lineHeight: 21 },
  warningBanner: { color: '#fff2be', marginTop: 10 },
  tabBar: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  tabButton: { flex: 1, backgroundColor: '#ddd8ea', borderRadius: 18, paddingVertical: 12, paddingHorizontal: 14 },
  tabButtonActive: { backgroundColor: '#3c3a56' },
  tabLabel: { color: '#3c3a56', fontWeight: '700', textAlign: 'center' },
  tabLabelActive: { color: '#fff' },
  routeBanner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14, paddingHorizontal: 4 },
  routeText: { color: '#5f6d64', fontSize: 13, fontWeight: '600' },
  routeActionText: { color: '#3c3a56', fontSize: 13, fontWeight: '700' },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 14, marginHorizontal: -4 },
  statCard: { width: '50%', paddingHorizontal: 4, marginBottom: 8 },
  statValue: { backgroundColor: '#56507d', color: '#fff', fontSize: 22, fontWeight: '700', paddingTop: 14, paddingHorizontal: 14, borderTopLeftRadius: 16, borderTopRightRadius: 16 },
  statLabel: { backgroundColor: '#56507d', color: '#dfdcff', paddingHorizontal: 14, paddingBottom: 14, borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },
  card: { backgroundColor: '#fffaf2', borderRadius: 22, padding: 18, borderWidth: 1, borderColor: '#eadfca', marginBottom: 16 },
  infoBanner: { color: '#8b5e34', backgroundColor: '#fff3cd', borderRadius: 14, padding: 12, marginBottom: 12 },
  errorBanner: { color: '#991b1b', backgroundColor: '#fee2e2', borderRadius: 14, padding: 12, marginBottom: 12 },
  input: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#d8ddd6', paddingHorizontal: 14, paddingVertical: 12, color: '#1f2937', fontSize: 15, marginBottom: 12 },
  primaryButton: { backgroundColor: '#7566d8', borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  navRow: { flexDirection: 'row', gap: 8, marginBottom: 16, justifyContent: 'flex-end' },
  logoutChip: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: '#6b5b55' },
  logoutText: { color: '#fff', fontWeight: '700' },
  sectionTitle: { color: '#18231c', fontSize: 22, fontWeight: '700', marginBottom: 12, marginTop: 6 },
  metricRow: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#fff', borderRadius: 14, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#e4dfd5' },
  metricLabel: { color: '#425046', fontWeight: '600', textTransform: 'capitalize' },
  metricValue: { color: '#3c3a56', fontWeight: '700' },
  listCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5', marginBottom: 10 },
  listTitle: { color: '#18231c', fontSize: 17, fontWeight: '700', marginBottom: 4 },
  listMeta: { color: '#5f6d64', fontSize: 13 },
  listHint: { color: '#3c3a56', fontSize: 12, fontWeight: '700', marginTop: 8 },
  detailGrid: { gap: 10 },
  detailSection: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#e4dfd5' },
  detailSectionTitle: { color: '#18231c', fontSize: 16, fontWeight: '700', marginBottom: 8 },
  bulletRow: { color: '#425046', fontSize: 14, lineHeight: 20, marginBottom: 6 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  actionChip: { backgroundColor: '#ece9ff', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 10 },
  actionChipActive: { backgroundColor: '#56507d' },
  actionChipText: { color: '#3c3a56', fontWeight: '700' },
  actionChipTextActive: { color: '#fff' },
  secondaryButton: { backgroundColor: '#6b5b55', borderRadius: 14, paddingVertical: 12, alignItems: 'center', marginTop: 10 },
  reviewTitle: { color: '#18231c', fontSize: 18, fontWeight: '700', marginBottom: 6 },
  reviewMeta: { color: '#5f6d64', fontSize: 13, fontWeight: '600' },
  monoPreview: { color: '#425046', fontFamily: 'monospace', fontSize: 12, lineHeight: 18 }
});